[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "httpx"
description = "The next generation HTTP client."
authors = [{ name = "Tom Christie", email = "tom@tomchristie.com" }]
license = { text = "BSD 3-Clause License" }
requires-python = ">=3.7"
dependencies = [
    "certifi",
    "sniffio",
    "rfc3986[idna2008]>=1.3,<2",
    "httpcore>=0.15.0,<0.16.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Framework :: AsyncIO",
    "Framework :: Trio",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
]
dynamic = ["version", "readme"]

[tool.setuptools]
license-files = ["LICENSE.md"]
package-data = { "httpx" = ["py.typed"] }
include-package-data = true
zip-safe = false

[project.optional-dependencies]
http2 = ["h2>=3,<5"]
socks = ["socksio==1.*"]
brotli = [
    "brotli; platform_python_implementation == 'CPython'",
    "brotlicffi; platform_python_implementation != 'CPython'",
]
cli = ["click==8.*", "rich>=10,<13", "pygments==2.*"]

[project.urls]
Homepage = "https://www.python-httpx.org"
Changelog = "https://github.com/encode/httpx/blob/master/CHANGELOG.md"
Documentation = "https://www.python-httpx.org"
Source = "https://github.com/encode/httpx"

[project.scripts]
httpx = "httpx:main"

[tool.setuptools.dynamic]
version = { attr = "httpx.__version__.__version__" }
readme = { file = ["README.md", "CHANGELOG.md"], content-type = "text/markdown" }
